export const ACTIONS = {
  ADD_TODO: 'ADD_TODO',
  SET_CHECKED: 'SET_CHECKED',
  GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
  GET_PHOTOS_REQUEST: 'GET_PHOTOS_REQUEST',
  GET_PHOTOS_FAILURE: 'GET_PHOTOS_FAILURE',
  GET_ONE_PHOTO_SUCCESS: 'GET_ONE_PHOTO_SUCCESS',
  GET_ONE_PHOTO_REQUEST: 'GET_ONE_PHOTO_REQUEST',
  GET_ONE_PHOTO_FAILURE: 'GET_ONE_PHOTO_FAILURE',
};
